(in-package :nba-highlights-bot)

(defparameter *team-aliases*
  '(("hawks" . "Atlanta Hawks")
    ("atlanta" . "Atlanta Hawks")
    ("at" . "Atlanta Hawks")
    ("celtics" . "Boston Celtics")
    ("boston" . "Boston Celtics")
    ("bos" . "Boston Celtics")
    ("nets" . "Brooklyn Nets")
    ("brooklyn" . "Brooklyn Nets")
    ("bkn" . "Brooklyn Nets")
    ("hornets" . "Charlotte Hornets")
    ("charlotte" . "Charlotte Hornets")
    ("cha" . "Charlotte Hornets")
    ("bulls" . "Chicago Bulls")
    ("chicago" . "Chicago Bulls")
    ("chi" . "Chicago Bulls")
    ("cavaliers" . "Cleveland Cavaliers")
    ("cavs" . "Cleveland Cavaliers")
    ("cleveland" . "Cleveland Cavaliers")
    ("cle" . "Cleveland Cavaliers")
    ("mavericks" . "Dallas Mavericks")
    ("mavs" . "Dallas Mavericks")
    ("dallas" . "Dallas Mavericks")
    ("dal" . "Dallas Mavericks")
    ("nuggets" . "Denver Nuggets")
    ("denver" . "Denver Nuggets")
    ("den" . "Denver Nuggets")
    ("pistons" . "Detroit Pistons")
    ("detroit" . "Detroit Pistons")
    ("det" . "Detroit Pistons")
    ("warriors" . "Golden State Warriors")
    ("golden state" . "Golden State Warriors")
    ("gsw" . "Golden State Warriors")
    ("rockets" . "Houston Rockets")
    ("houston" . "Houston Rockets")
    ("hou" . "Houston Rockets")
    ("pacers" . "Indiana Pacers")
    ("indiana" . "Indiana Pacers")
    ("ind" . "Indiana Pacers")
    ("clippers" . "LA Clippers")
    ("la clippers" . "LA Clippers")
    ("lac" . "LA Clippers")
    ("lakers" . "Los Angeles Lakers")
    ("los angeles lakers" . "Los Angeles Lakers")
    ("lal" . "Los Angeles Lakers")
    ("grizzlies" . "Memphis Grizzlies")
    ("memphis" . "Memphis Grizzlies")
    ("mem" . "Memphis Grizzlies")
    ("heat" . "Miami Heat")
    ("miami" . "Miami Heat")
    ("mia" . "Miami Heat")
    ("bucks" . "Milwaukee Bucks")
    ("milwaukee" . "Milwaukee Bucks")
    ("mil" . "Milwaukee Bucks")
    ("timberwolves" . "Minnesota Timberwolves")
    ("wolves" . "Minnesota Timberwolves")
    ("minnesota" . "Minnesota Timberwolves")
    ("min" . "Minnesota Timberwolves")
    ("pelicans" . "New Orleans Pelicans")
    ("pels" . "New Orleans Pelicans")
    ("new orleans" . "New Orleans Pelicans")
    ("nop" . "New Orleans Pelicans")
    ("knicks" . "New York Knicks")
    ("new york" . "New York Knicks")
    ("nyk" . "New York Knicks")
    ("thunder" . "Oklahoma City Thunder")
    ("oklahoma city" . "Oklahoma City Thunder")
    ("okc" . "Oklahoma City Thunder")
    ("magic" . "Orlando Magic")
    ("orlando" . "Orlando Magic")
    ("orl" . "Orlando Magic")
    ("76ers" . "Philadelphia 76ers")
    ("sixers" . "Philadelphia 76ers")
    ("philadelphia" . "Philadelphia 76ers")
    ("phi" . "Philadelphia 76ers")
    ("suns" . "Phoenix Suns")
    ("phoenix" . "Phoenix Suns")
    ("phx" . "Phoenix Suns")
    ("blazers" . "Portland Trail Blazers")
    ("trail blazers" . "Portland Trail Blazers")
    ("portland" . "Portland Trail Blazers")
    ("por" . "Portland Trail Blazers")
    ("kings" . "Sacramento Kings")
    ("sacramento" . "Sacramento Kings")
    ("sac" . "Sacramento Kings")
    ("spurs" . "San Antonio Spurs")
    ("san antonio" . "San Antonio Spurs")
    ("sas" . "San Antonio Spurs")
    ("raptors" . "Toronto Raptors")
    ("toronto" . "Toronto Raptors")
    ("tor" . "Toronto Raptors")
    ("jazz" . "Utah Jazz")
    ("utah" . "Utah Jazz")
    ("uta" . "Utah Jazz")
    ("wizards" . "Washington Wizards")
    ("washington" . "Washington Wizards")
    ("was" . "Washington Wizards"))
  "Alist mapping team alias strings to full team names.")

(defun resolve-team (input)
  "Resolve a team alias string to the full team name.
Returns the full team name string, or NIL if no match found.
Case-insensitive."
  (let ((downcased (string-downcase (string-trim " " input))))
    (cdr (assoc downcased *team-aliases* :test #'string=))))
